version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
    container_name: phishing_api
    env_file:
      - .env
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - .:/app                       # Monta o código da aplicação para facilitar o desenvolvimento
      - ./logs:/app/logs               # Mapeia a pasta 'logs' para persistir os logs (crie a pasta logs se ainda não existir)
      - ./db.sqlite3:/app/db.sqlite3:Z # Monta o arquivo do banco SQLite; certifique-se de que este arquivo esteja na raiz
    networks:
      - app_network
    command: >
      uvicorn app.backend.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile         # Utilize apenas "Dockerfile" pois o contexto já é app/frontend
    container_name: phishing_frontend
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./app/frontend:/app           # Monta o código do frontend (ideal para desenvolvimento)
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
