version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
    container_name: phishing_api
    env_file:
      - .env
    volumes:
      - .:/app              # código + db.sqlite3 na raiz do host
      - ./logs:/app/logs
    ports:
      - "${API_PORT:-8000}:8000"
    networks:
      - app_network
    command: >
      uvicorn app.backend.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: phishing_frontend
    env_file:
      - .env
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    networks:
      - app_network
    command: npm start

networks:
  app_network:
    driver: bridge
